// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIvaGjDpDpGaEYMEfoJNp0NYzS91vptkw',
    appId: '1:54288514119:web:524b0db0634f77321c4562',
    messagingSenderId: '54288514119',
    projectId: 'f-attendance-app',
    authDomain: 'f-attendance-app.firebaseapp.com',
    storageBucket: 'f-attendance-app.firebasestorage.app',
    measurementId: 'G-F5M8ZGM08V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEHRxnMX_schvIhVQzqISD1XAERDNro1M',
    appId: '1:54288514119:android:b34d1f4648b0c7ee1c4562',
    messagingSenderId: '54288514119',
    projectId: 'f-attendance-app',
    storageBucket: 'f-attendance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmiDG9eGz6XUrRx2FV8MjwXWBIUt7EQWQ',
    appId: '1:54288514119:ios:bea5cec92b97d3231c4562',
    messagingSenderId: '54288514119',
    projectId: 'f-attendance-app',
    storageBucket: 'f-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.fStar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmiDG9eGz6XUrRx2FV8MjwXWBIUt7EQWQ',
    appId: '1:54288514119:ios:bea5cec92b97d3231c4562',
    messagingSenderId: '54288514119',
    projectId: 'f-attendance-app',
    storageBucket: 'f-attendance-app.firebasestorage.app',
    iosBundleId: 'com.example.fStar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIvaGjDpDpGaEYMEfoJNp0NYzS91vptkw',
    appId: '1:54288514119:web:262be6358f0f2cb11c4562',
    messagingSenderId: '54288514119',
    projectId: 'f-attendance-app',
    authDomain: 'f-attendance-app.firebaseapp.com',
    storageBucket: 'f-attendance-app.firebasestorage.app',
    measurementId: 'G-9PTCQLM346',
  );
}
